timeout: 5
hidenocheck: false
loadbalancers:
    Haproxy1:
        name: "Haproxy1"
        urls:
            - "http://10.1.1.1:8181/;csv;norefresh"
            - "http://10.1.1.1:8182/;csv;norefresh"
            - "http://10.1.1.1:8183/;csv;norefresh"
            - "http://10.1.1.1:8184/;csv;norefresh"
    Haproxy2: 
        name: "Haproxy2"
        options:
           "ignoreHighSessions": true
        urls:
            - "http://10.1.2.1:8181/;csv;norefresh"
            - "http://10.1.2.1:8182/;csv;norefresh"
    g3: 
        name: "Haproxy3"
        urls:
            - "http://10.1.3.1:8181/;csv;norefresh"
            - "http://10.1.3.1:8182/;csv;norefresh"
            - "http://10.1.3.1:8183/;csv;norefresh"
            - "http://10.1.3.1:8184/;csv;norefresh"
