timeout: 5
hidenocheck: false
loadbalancers:
    g1:
        name: "Haproxy 1" 
        urls:
            - "http://10.1.1.1:8181/;csv;norefresh"
            - "http://10.1.1.1:8182/;csv;norefresh"
            - "http://10.1.1.1:8183/;csv;norefresh"
            - "http://10.1.1.1:8184/;csv;norefresh"
    g2: 
        name: "Haproxy 2" 
        urls:
            - "http://10.1.2.1:8181/;csv;norefresh"
            - "http://10.1.2.1:8182/;csv;norefresh"
    g3: 
        name: "Haproxy 3" 
        urls:
            - "http://10.1.3.1:8181/;csv;norefresh"
            - "http://10.1.3.1:8182/;csv;norefresh"
            - "http://10.1.3.1:8183/;csv;norefresh"
            - "http://10.1.3.1:8184/;csv;norefresh"
